apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: postgres-tasks
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: narodees/postgres_tasks-grafana:0.2  # custom grafana image
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                    name: my-secret
                    key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: my-secret
                    key: GF_SECURITY_ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: postgres-tasks
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
