apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: postgres-tasks
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki
          args:
            - -config.file=/etc/loki/loki-config.yml
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki
      volumes:
        - name: loki-config-volume
          configMap:
            name: loki-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: postgres-tasks
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
