{{- $module := .Values.minio -}}
{{- $module_name := "minio" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $module_name }}-secret-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := $module.env }}
  {{- $key | toString | nindent 2 }}: {{ $value | toString | quote }}
{{- end }}
