version: '3.9'

services:
  django:
    container_name: django
    restart: unless-stopped
    build: postgres_tasks
    image: narodees/postgres_tasks-django
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - backend-network
      - rabbit-network
      - monitoring-network
    command: supervisord

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:

volumes:
  django_static_volume:
  logs_volume:
