version: '3.9'

services:
  django:
    container_name: django
    restart: unless-stopped
    build: postgres_tasks
    env_file:
      - ./.env
    volumes:
      - ./postgres_tasks/supervisor/logs:/var/log
      -  django_static_volume:/server/static
      - ./postgres_tasks:/server/
      - logs_volume:/var/log
    ports:
      - 8000:8000
    networks:
      - backend-network
      - rabbit-network
      - monitoring-network
    command: supervisord

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:

volumes:
  django_static_volume:
  logs_volume:
