version: '3.9'

services:
  django:
    container_name: django
    restart: unless-stopped
    build: postgres_tasks
    image: narodees/postgres_tasks-django
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - backend-network
      - rabbit-network
      - monitoring-network
    volumes:
      - logs_volume:/var/log
    command: supervisord

  django-postgres:
    container_name: django-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - backend-network
    env_file:
      - ./.env

  sandbox-postgres:
    container_name: sandbox-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 54321:5432
    networks:
      - backend-network
    env_file:
      - ./.env

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:

volumes:
  django_static_volume:
  logs_volume:
