version: "3.9"

services:
  django-postgres:
    container_name: django-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - backend-network
    env_file:
      - ./.env

  sandbox-postgres:
    container_name: sandbox-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 54321:5432
    networks:
      - backend-network
    
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - rabbit-network
      - monitoring-network
    ports:
      - 15672:15672
      - 15692:15692
    env_file:
      - ./.env

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:
