version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - rabbit-network
      - monitoring-network
    ports:
      - 15672:15672
      - 15692:15692
    env_file:
      - ./.env

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:
