version: "3.9"

services:
    postgres:
        container_name: postgres_django
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: adminka
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: django
            PGDATA: /var/lib/postgresql/data/db/
        
    sendbox_postgres:
        container_name: sendbox_postgres
        image: postgres
        restart: unless-stopped
        ports:
            - 54321:5432
        environment:
            POSTGRES_USER: adminka
            POSTGRES_PASSWORD: qwerty
            POSTGRES_DB: sandbox
            PGDATA: /var/lib/postgresql/data/db/
        
    django:
        container_name: django
        restart: unless-stopped
        build:
            context: postgres_tasks/
        depends_on:
            - postgres
        env_file:
            - ./.env
        volumes:
            - ./postgres_tasks:/server
        ports:
            - 8000:8000
        command: >
              sh -c " 
              python manage.py runserver 0.0.0.0:8000 "
    
              
    worker:
        container_name: worker
        restart: unless-stopped
        build:
            context: postgres_tasks/
        depends_on:
            - postgres
        env_file:
            - ./.env
        volumes:
            - ./postgres_tasks:/server
        command: >
            sh -c "
            celery -A postgres_tasks worker -l INFO"
    

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: cool_rabbit
