version: "3.9"

services:
    postgres:
        container_name: postgres_django
        image: postgres
        restart: unless-stopped
        expose:
            - 5432
        ports:
            - 5432:5432
        env_file:
            - ./.env
        
    sandbox_postgres:
        container_name: sandbox_postgres
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        expose:
            - 5432
        ports:
            - 54321:5432   
        env_file:
            - ./.env
        
    django:
        container_name: django
        restart: unless-stopped
        build:
            context: postgres_tasks/
        depends_on:
            - postgres
        env_file:
            - ./.env
        volumes:
            - ./postgres_tasks:/server
        ports:
            - 8000:8000
        command: >
              sh -c " 
              python manage.py runserver 0.0.0.0:8000 "
    
              
    worker:
        container_name: worker
        restart: unless-stopped
        build:
            context: postgres_tasks/
        depends_on:
            - postgres
        env_file:
            - ./.env
        volumes:
            - ./postgres_tasks:/server
        command: >
            sh -c "
            celery -A postgres_tasks worker -l INFO -f logs/celery.log"
    

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        expose:
            - 5672
            - 15672
        env_file:
            - ./.env
