{{- $module := .Values.loki -}}
{{- $module_name := "loki" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $module_name }}
  template:
    metadata:
      labels:
        app: {{ $module_name }}
    spec:
      containers:
        - name: {{ $module_name }}
          image: {{ $module.image.repository }}:{{ $module.image.tag }}
          imagePullPolicy: {{ $module.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/loki-config.yml
          resources:
            {{- toYaml $module.resources | nindent 12 }}
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config-volume
              mountPath: /etc/loki
      volumes:
        - name: loki-config-volume
          configMap:
            name: {{ $module_name }}-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $module_name }}
  ports:
  - port: 3100
    targetPort: 3100
