apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  namespace: postgres-tasks
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'django'
        static_configs:
          - targets: ['django:8000']

      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-exporter:9113']
      
      - job_name: 'rabbit'
        static_configs:
          - targets: ['rabbitmq:15692']
  
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints 
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'node-exporter'
            action: keep
