apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config-map
  namespace: postgres-tasks
data:
  promtail.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
    - job_name: django-log-scraper
      static_configs:
        - targets:
            - localhost
          labels:
            __path__: "/var/log/celery.log"
            app: celery
        - targets:
            - localhost
          labels:
            __path__: "/var/log/celery_beats.log"
            app: celery-beats
        - targets:
            - localhost
          labels:
            __path__: "/var/log/django.log"
            app: django
        - targets:
            - localhost
          labels:
            __path__: "/var/log/access.log"
            app: nginx-access
        - targets:
            - localhost
          labels:
            __path__: "/var/log/error.log"
            app: nginx-error

