version: '3.9'

services:
  prometheus:
      container_name: prometheus
      image: prom/prometheus
      ports:
         - 9090:9090
      networks:
        - monitoring-network
        - backend-network
        - frontend-network
      volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
      container_name: grafana
      build: monitoring/grafana
      ports:
        - 3000:3000
      networks:
        - monitoring-network
      volumes:
        - ./monitoring/grafana/data:/var/lib/grafana

networks:
  monitoring-network:
  rabbit-network:
  backend-network:
  frontend-network:
