apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: django-postgres
  namespace: postgres-tasks
spec:
  serviceName: django-postgres
  replicas: 1
  selector:
    matchLabels:
      app: django-postgres
  volumeClaimTemplates:
    - metadata:
        name: django-postgres-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"  # to be changed
        resources:
          requests:
            storage: "500Mi" 
  template:
    metadata:
      labels:
        app: django-postgres
    spec:
      containers:
        - name: django-postgres
          image: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: django-postgres-volume
              mountPath: /var/lib/postgresql/data
              readOnly: false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: django-postgres
  namespace: postgres-tasks
spec:
  selector:
    app: django-postgres
  ports:
    - port: 5432
      targetPort: 5432
