apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-postgres
  template:
    metadata:
      labels:
        app: sandbox-postgres
    spec:
      containers:
        - name: sandbox-postgres
          image: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-postgres
spec:
  selector:
    app: sandbox-postgres
  ports:
    - port: 5432
      targetPort: 5432
