apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sandbox-postgres
  namespace: postgres-tasks
spec:
  serviceName: sandbox-postgres
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-postgres
  volumeClaimTemplates:
    - metadata:
        name: sandbox-postgres-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"  # to be changed
        resources:
          requests:
            storage: "500Mi"  
  template:
    metadata:
      labels:
        app: sandbox-postgres
    spec:
      containers:
        - name: sandbox-postgres
          image: postgres
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: sandbox-postgres-volume
              mountPath: /var/lib/postgresql/data
              readOnly: false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-postgres
  namespace: postgres-tasks
spec:
  selector:
    app: sandbox-postgres
  ports:
    - port: 5432
      targetPort: 5432
