{{- $module := index .Values "nginx-exporter" -}}
{{- $module_name := "nginx-exporter" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $module_name }}
  template:
    metadata:
      labels:
        app: {{ $module_name }}
    spec:
      containers:
        - name: {{ $module_name }}
          image: {{ $module.image }}:{{ $module.tag }}
          args: ["-nginx.scrape-uri", "http://nginx:80/metrics"]
          resources:
            {{- toYaml $module.resources | nindent 12 }}
          ports:
            - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $module_name }}
  ports:
    - port: 9113
      targetPort: 9113
