apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: postgres-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: logs
          hostPath: 
            path: /var/log
      restartPolicy: Always
      containers:
        - name: promtail
          image: grafana/promtail
          args: [--config.file=/etc/promtail/promtail.yml]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
              - name: promtail-conf
                mountPath: /etc/promtail
              - name: logs
                mountPath: /var/log
                readOnly: true
        - name: nginx
          image: narodees/postgres_tasks-nginx:0.1  # custom nginx image
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-volume
              mountPath: /www/data/static
              readOnly: true
            - name: logs
              mountPath: /var/log/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: postgres-tasks
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
