apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: postgres-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
      restartPolicy: Always
      containers:
        - name: nginx
          image: narodees/postgres_tasks-nginx:0.1  # custom nginx image
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-volume
              mountPath: /www/data/static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: postgres-tasks
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
