version: '3.9'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: postgres_front
    image: narodees/postgres_tasks-nginx
    env_file:
      - ./.env
    ports:
      - 80:80
    networks:
      - frontend-network
      - backend-network
      - monitoring-network
    volumes:
      - django_static_volume:/www/data/static:ro
      - logs_volume:/var/log/nginx
  
  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter
    restart: unless-stopped
    expose:
      - 9113
    networks:
      - monitoring-network
      - frontend-network
    command: -nginx.scrape-uri http://nginx:80/metrics

networks:
    monitoring-network:
    rabbit-network:
    backend-network:
    frontend-network:

volumes:
  django_static_volume:
  logs_volume: