version: '3.9'

services:

  nginx:
    container_name: nginx
    restart: unless-stopped
    build: postgres_front
    image: narodees/postgres_tasks-nginx
    env_file:
      - ./.env
    ports:
      - 80:80
    networks:
      - frontend-network
      - backend-network
      - monitoring-network
    volumes:
      - ./postgres_front/nginx:/etc/nginx/conf.d
      - django_static_volume:/www/data/static:ro
      - logs_volume:/var/log/nginx

networks:
    monitoring-network:
    rabbit-network:
    backend-network:
    frontend-network:

volumes:
  django_static_volume:
  logs_volume: