namespace: postgres-tasks

minio:
  image:
    repository: bitnami/minio
    tag: latest
    pullPolicy: IfNotPresent

  storageResources:
    requests:
      storage: 1Gi

  env:
    MINIO_ROOT_USER: adminka1
    MINIO_ROOT_PASSWORD: adminka1
