apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  DEBUG: '0'
  POSTGRES_DB: sandbox
  DJANGO_SECRET_KEY: some_very_secret_key
  POSTGRES_USER: adminka
  POSTGRES_PASSWORD: qwerty
  RABBITMQ_DEFAULT_USER: rabbit
  RABBITMQ_DEFAULT_PASS: cool_rabbit
