apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: gstykalin@mail.ru
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: lets-encrypt-secret
      key: access-token
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik  # change to nginx in Kubernetes
      selector: {}
  