# Generated by Django 4.1.7 on 2023-03-16 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2023, 3, 16, 20, 28, 30, 88429, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('creation_script', models.FileField(upload_to='creation_scripts')),
                ('check_script', models.FileField(upload_to='check_scripts')),
                ('db_structure', models.ImageField(upload_to='dbs_structure')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('active_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activetask')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='down', max_length=10)),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usertask')),
            ],
        ),
        migrations.AddField(
            model_name='activetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
