# Generated by Django 4.1.7 on 2023-03-17 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 8, 8, 2, 403106, tzinfo=datetime.timezone.utc)),
        ),
    ]
