# Generated by Django 4.1.7 on 2023-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinfo',
            name='moves_performed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='moves_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
