# Generated by Django 4.1.7 on 2023-03-18 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activetask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 18, 31, 28, 491475, tzinfo=datetime.timezone.utc)),
        ),
    ]
