# Generated by Django 4.1.7 on 2023-04-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_databaseinfo_moves_performed_task_moves_count'),
        ('core', '0003_user_email_confirmed'),
    ]

    operations = [
    ]
