apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
  namespace: postgres-tasks
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
