apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
  namespace: postgres-tasks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
