{{- $module := .Values.django -}}
{{- $module_name := "django" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $module_name }}
  template:
    metadata:
      labels:
        app: {{ $module_name }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: {{ $module_name }}
          image: {{ $module.image.repository }}:{{ $module.image.tag }}
          imagePullPolicy: {{ $module.image.pullPolicy }}
          command: ["supervisord"]
          resources:
            {{- toYaml $module.resources | nindent 12 }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-volume
              mountPath: /server/static
            - name: logs
              mountPath: /var/log
          envFrom:
            - secretRef:
                name: {{ $module_name }}-secret-env

        {{- include "promtail.container" . | nindent 8 }}

      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: logs
          hostPath:
            path: /var/log
        {{- include "promtail.volumes" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $module_name }}
  ports:
    - port: 8000
      targetPort: 8000
