{{- $module := .Values.django -}}
{{- $module_name := "django" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $module_name }}-secret-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := $module.env }}
  {{- toString $key | nindent 2 }}: {{ $value | toString | quote }}
{{- end }}