name: test, build and push images to Docker Hub
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: 'Create backend env file for testing'
        run: |
          echo "${{ secrets.ENV_FILE_TESTS }}" > .env
      - name: 'Create frontend env file for testing'
        run: |
          echo "${{ secrets.FRONT_ENV_TEST }}" > ./postgres_front/.env.production
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run with Docker compose
        run: |
          ./scripts/build_core.sh
          ./scripts/start_core.sh
      - name: Wait for startup
        run: sleep 3
      - name: Run Django tests
        run:
          docker exec django python3 manage.py test core.tests

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: 'Create frontend env file for testing'
        run: |
          echo "${{ secrets.FRONT_ENV }}" > ./postgres_front/.env.production
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with Docker compose
        run: |
          ./scripts/build_and_push_all.sh
