name: Build and push images to Docker Hub
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run with Docker compose
        run: |
          ./build_core.sh
          ./start_core.sh
      - name: Wait for startup
        run: sleep 3
      - name: Run Django tests
        run:
          docker exec django python3 manage.py test core.tests  

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with Docker compose
        run: |
          ./build_core.sh
          ./push_core.sh
